### ISSUE TITLE
Version selection appends a zero to all versions, even if there's no ".0"

### ISSUE THREAD

**Issue by NotMyFault** [jamesward/javadoccentral#15]
https://javadocs.dev/io.jenkins.archetypes/archetypes-parent for example, suggests 1.21.0 as latest version, but that version doesn't exist and yields
![Screenshot 2023-10-05 at 20 23 27](https://github.com/jamesward/javadoccentral/assets/13383509/01a9e26a-5370-4408-8819-e4db223af5e7)
upon click.

Versions not following the format X.X.X seem to have a zero appended by default, even if that turns their version invalid:
![Screenshot 2023-10-05 at 20 25 55](https://github.com/jamesward/javadoccentral/assets/13383509/9bfb7ac5-acd3-4f8a-8b31-5f8f96b73b96)
Valid ones are https://repo.maven.apache.org/maven2/io/jenkins/archetypes/archetypes-parent/ and require modification of the URL to get the proper results.

**Comment by jamesward** [comment]
Whoops! Thanks for reporting.  I've fixed it:
https://github.com/jamesward/zio-mavencentral/commit/7169abb54ae2ce38562e1c8bf6256006e094c6fc

And will get this rolled out to prod shortly.

**Comment by jamesward** [comment]
This will be in prod in about 10 minutes.

**Comment by NotMyFault** [comment]
Thanks for the swift fix!
https://javadoc.io/ downtime made me discover this tool to get my builds running again, and it works like a charm.
It likely will be my permanent replacement, and javadocs.dev is open source too.

Thanks a lot for maintaining such an amazing tool ❤️

**Comment by jamesward** [comment]
Thanks!  The fix has been deployed.  Note that the referenced artifact (https://javadocs.dev/io.jenkins.archetypes/archetypes-parent) doesn't actually have javadoc-jars so that part still won't work but at least the versions are fixed.

**Comment by NotMyFault** [comment]
> Thanks! The fix has been deployed. Note that the referenced artifact ([javadocs.dev/io.jenkins.archetypes/archetypes-parent](https://javadocs.dev/io.jenkins.archetypes/archetypes-parent)) doesn't actually have javadoc-jars so that part still won't work but at least the versions are fixed.

Yeah, I know, no worries, but I didn't have a project without semver at hand, which is at the central repo, when I submitted the issue 😅
